# Generated by Django 4.2.6 on 2023-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_alter_files_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
